### ISSUE TITLE
SODA-A config

### ISSUE THREAD

**Issue by 622tongtong** [shaunyuan22/CFINet#10]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

I wonder if it is possible to upload the config file of obb task based on SODA-A. Cus there is only hbb config. Thank you so much for sharing.

**Comment by shaunyuan22** [comment]
Sry, this is not in ou plan. 
The code structure of mmrot is highly similar to that of mmdet, and `RotatedRPN` outputs hbb proposals and the operation about region features in `feature_imitation_roi_head.py` has nothing to do with hbb or obb, which means just transfering the codes in `crpn_head.py` and `feature_imitation_roi_head.py` to `rotated_rpn.py` and `rotate_standard_roi_head.py` will work

**Comment by Alexwong-1024** [comment]
According to what you mean, I only need to modify your improved codes in crpn_head.py and feature_imitation_roi_head.py in mmdet, and modify them in the corresponding places of rotated_rpn.py and rotate_standard_roi_head.py in mmrotate? Then do I use the mmrotate module when training? Based on this modification, I can copy your configs/cfinet/faster_rcnn_r50_fpn_cfinet_1x.py file to SODA-mmrotate
/configs/, and then use SODA-mmrotate’s train.py for training, or should you stay in the original CFINet file and use train.py for training? Looking forward to your reply. @shaunyuan22

**Comment by 622tongtong** [comment]
OKay, thanks for your replying.

**Comment by Alexwong-1024** [comment]
This is just my idea. I have just started in this direction. If you try it successfully, can you share how to modify it? Thank you！！！

**Comment by shaunyuan22** [comment]
> According to what you mean, I only need to modify your improved codes in crpn_head.py and feature_imitation_roi_head.py in mmdet, and modify them in the corresponding places of rotated_rpn.py and rotate_standard_roi_head.py in mmrotate? Then do I use the mmrotate module when training? Based on this modification, I can copy your configs/cfinet/faster_rcnn_r50_fpn_cfinet_1x.py file to SODA-mmrotate /configs/, and then use SODA-mmrotate’s train.py for training, or should you stay in the original CFINet file and use train.py for training? Looking forward to your reply. @shaunyuan22

exactly right, maybe it takes a few modifications when copying the config

**Comment by Jmipar-k** [comment]
Hello and happy new year, @shaunyuan22. 

Since, you have the experimental results of CFINet on SODA-A dataset on your paper.

Could you just share the modified version of the config file(faster_rcnn_r50_fpn_cfinet_1x), crpn_head.py, and feature_imitation_roi_head.py so we could just apply it directly to the SODA-mmrotate repo?
(Or has anybody succeeded in modifying and training cfinet with SODA-A dataset?)

I am new to this mm toolbox and it is not easy for me to modify the codes...

I am looking forward for you help and reply!

P.S.
For the SODA-D dataset, I do not understand how I can achieve the annotation_wo_ignore. The SODA-A dataset has generate_wo_ignore.py code for obtaining AnnsWoIgnore(rawdata), but i could not find the code for SODA-D. I would appreciate it if someone could help me figure this out!

Thank you so much!

**Comment by hetunsanhao** [comment]
> This is just my idea. I have just started in this direction. If you try it successfully, can you share how to modify it? Thank you！！！这只是我的想法。我刚刚开始在这个方向上。如果你尝试成功，能否分享一下如何修改它？谢谢！！！

Hello.Have you made it on the SODA-A? Could you please shared the modified codes which have been mentioned above? I would appreciate it very much.
