### ISSUE TITLE
Extracting  aug_hq_gt_bboxes

### ISSUE THREAD

**Issue by 622tongtong** [shaunyuan22/CFINet#22]
### What's the feature?

The code about extracting features of aug_hq_gt_bboxes is as following:
aug_hq_gt_rois = arb2roi([aug_hq_gt_bboxes], bbox_type=self.bbox_head.start_bbox_type)
aug_hq_gt_roi_feats = self.aug_roi_extractor(x, aug_hq_gt_rois)

Through arb2roi, the image indexes of all aug_hq_gt_rois are 0, however, these gt bboxes are from different images.
It may be my misunderstanding. Could you please provide an explanation?

**Comment by shaunyuan22** [comment]
1. i guess you mean `bbox2roi` instead of `arb2roi` cause there is no `arb2roi` in our codes;
2. if you look line 345 of feature_imitation_roi_head as follows: https://github.com/shaunyuan22/CFINet/blob/2167eebdc420046165e78a7555e40b044355cb58/mmdet/models/roi_heads/feature_imitation_roi_head.py#L345
you will find all the `hq_gt_rois` and `hq_gt_roi_feats` are processed at image level and we only handle one image at a time, hence the indexes are 0 and actually, the indexes here make no sense cause they are not use at all .
